# GitHub
username: odmdev
repo:     odmdev.github.io
branch:   source

GIT_NAME: "Jeremy Pichon"
GIT_EMAIL: "jeremy.pichon@fr.ibm.com"

# Jekyll source / destination
source:      .
destination: _site

